### ISSUE TITLE
A question about case study

### ISSUE THREAD

**Issue by zzhuncle** [geekinglcq/HRec#2]
Hello, your work is excellent, so I want to follow and site. But i has a small question. I want to ask about the feature comparison between movies adapted from books in case study. Because the data is desensitized, it cannot be reproduced. Could you provide the corresponding relationship between books and movies adapted? Thank you very much !!!

**Comment by zzhuncle** [comment]
![image](https://user-images.githubusercontent.com/57178872/197528235-44f95b96-fa84-4043-bbd0-181b8d3dbfd6.png)

**Comment by geekinglcq** [comment]
![image](https://user-images.githubusercontent.com/9047780/197674832-2d1c4b49-cdb0-4f5c-b929-32be1e52975d.png)
Hello, thank you for your attention. Here is the raw data (euclidean distance) of these pairs. But I am not sure if it is what you want, therefore I upload the embeddings of these books & movies as well.
---->[data.pickle.zip](https://github.com/geekinglcq/HRec/files/9856927/data.pickle.zip)

**Comment by zzhuncle** [comment]
It's so kind of you, and thanks very much, but maybe I haven't said clearly that I want to get the information between the item id and the correspond item name, for example, the item 0 correspondding to book 《Great Future》.
I'd appreciate very much if you could help.

**Comment by geekinglcq** [comment]
Oh, ic, here you are.
```
titles = ['20,000 miles under the sea', 'Robinson Crusoe', 'Orphan in the fog', "Lady Chatterley's Lover", 'Love in the Time of Cholera', 'The Silence of the Lambs', "Sophie's World", 'HP and the Order of the Phoenix', 'Great future', 'Mr. Holmes']  
books = [431, 79860, 136035, 73010, 30725, 87305, 17120, 466, 80808, 40825]
movies = [283365, 286206, 283680, 267130, 280868, 287955, 284779, 282593, 272194, 268860]
```

**Comment by zzhuncle** [comment]
Thanks very much !!!
