### ISSUE TITLE
A question about t-sne picture.

### ISSUE THREAD

**Issue by zzhuncle** [geekinglcq/HRec#3]
So sorry to bother you again. Can you please give us the visualization code of t-sne picture or tell me the library used for drawing. (I know sklearn.manifold.TSNE, but i got a scatter not a heat map, your picture looks so beautiful, so i really want to know how your can draw it. Thanks so much)

In addition, the original feature dimensions of books, music and movies are not consistent and cannot be directly reduced. Can you please tell us the method you use to reduce the different dimetions of three items?

**Comment by zzhuncle** [comment]
![digits_tsne-generated_1667330930 835894](https://user-images.githubusercontent.com/57178872/199225774-91793dc6-3723-47f7-abc9-1f8928e8d866.png)

**Comment by geekinglcq** [comment]
It might take a while to find the plot script. And I could do it this weekend if you do not hurry.  
/remind me about the thing in 3 days.

**Comment by zzhuncle** [comment]
It' s so kind of you. I'm not hurry, thanks so much~

**Comment by geekinglcq** [comment]
Sorry I couldn't find the original code to plot the figures. But I remember I used `seaborn.kedplot` and you can find it [here](https://seaborn.pydata.org/generated/seaborn.kdeplot.html). For t-sne, you can try `cuml` (https://github.com/rapidsai/cuml).  To avoid the inconsistent problem, I just select the common features of different types of items.

**Comment by zzhuncle** [comment]
It' so kind of you, Thanks very much~
